name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.1-xenial
          - swift:5.1-bionic
          - swift:5.2-xenial
          - swift:5.2-bionic
          - swift:5.2-focal
          - swift:5.2-centos8
          - swift:5.2-amazonlinux2
          - swift:5.3-xenial
          - swift:5.3-bionic
          - swift:5.3-focal
          - swift:5.3-centos8
          - swift:5.3-amazonlinux2
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: swift test --enable-test-discovery
  linux-5_4:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.4-xenial
          - swift:5.4-bionic
          - swift:5.4-focal
          - swift:5.4-centos8
          - swift:5.4-amazonlinux2
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests (without test discovery flag)
      run: swift test -Xswiftc -Xfrontend -Xswiftc -sil-verify-none
  linux-5_5-plus:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swiftlang/swift:nightly-5.5-xenial
          - swiftlang/swift:nightly-5.5-bionic
          - swiftlang/swift:nightly-5.5-focal
          - swiftlang/swift:nightly-5.5-centos8
          - swiftlang/swift:nightly-5.5-amazonlinux2
          - swiftlang/swift:nightly-xenial
          - swiftlang/swift:nightly-bionic
          - swiftlang/swift:nightly-focal
          - swiftlang/swift:nightly-centos8
          - swiftlang/swift:nightly-amazonlinux2
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: swift test
  osx:
    runs-on: macOS-11
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test --enable-test-discovery
